### PR TITLE
DownloadButton: Fix Installer and Portable Windows

### PR DESCRIPTION
**Pull request by RedDevilus**
It only says Download on any stable Windows download which isn't a good look.

PR 257 did this:
image

New Fix:

### CODE REVIEW

**Comment by RedDevilus** [comment]
Odd behaviour cuz no error catching duplicates or spilling to empty assets:

[`3854b71` (#258)](https://github.com/PCSX2/pcsx2-net-www/pull/258/commits/3854b711a0fafe75dc33269b703509fdb87934b8)

**Comment by RedDevilus** [comment]
[`1ff754d` (#258)](https://github.com/PCSX2/pcsx2-net-www/pull/258/commits/1ff754dec9607fad71d484411668c80a75c91d41)
image

**Comment by refractionpcsx2** [comment]
image

**Comment by RedDevilus** [comment]
image
image

**Comment by RedDevilus** [comment]
[`8655179` (#258)](https://github.com/PCSX2/pcsx2-net-www/pull/258/commits/8655179a2daf0ccd2547fd30cfb8ffbf3a5380a6)
Will produce:
image
image

Just older stable will show Installer or Portable, didn't really mess with Linux naming as it's annoying

**Comment by RedDevilus** [comment]
Even works fine on even older versions:

image

**Pull request merged**
